/**
 * Declare the Font Awesome Icons that is being used in the app here
 * You can read on how to use this in the FontAwesome website: https://fontawesome.com/how-to-use/on-the-web/using-with/react
 *
 */
import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faCheck,
  faEye,
  faEyeSlash,
  faAngleRight,
  faBell,
  faTimes,
  faMobile,
  faEnvelope,
  faLock,
  faPlus,
  faEllipsisH,
  faEllipsisV,
  faEdit,
  faTrash,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faCaretDown,
  faCaretUp,
  faPen,
  faStopwatch,
  faSquare,
  faCheckSquare,
  faCamera,
  faPhone,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faCheck,
  faEye,
  faEyeSlash,
  faAngleRight,
  faBell,
  faTimes,
  faMobile,
  faEnvelope,
  faLock,
  faPlus,
  faEllipsisH,
  faEllipsisV,
  faEdit,
  faTrash,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faCaretDown,
  faCaretUp,
  faPen,
  faStopwatch,
  faSquare,
  faCheckSquare,
  faCamera,
  faPhone,
);
